### ISSUE TITLE
Improving the UI of sessions details

### ISSUE THREAD

**Issue by heysadboy** [fossasia/open-event-android#1030]
The current UI of app is pretty but I feel like red color is used a lot.

- As the accent color and primary color of the app, both are shades of red so the floating action button should have a distinct background.
- There is no image in the upper part here so the toolbar better be in shape.
- The parts of the content can be divided by cards as the speakers could be multiple they should look more clickable. The flat layout without elevation doesn't feel like it.

It would be great if we could make the color of FABs a little contrasting from red so they are more visible as in the practice. For now I didn't change it, just wanted to know how you feel about it.

Before:

![screenshot_2017-01-19-20-25-38](https://cloud.githubusercontent.com/assets/22588035/22120419/9e574f6c-dea5-11e6-8895-de5ef2a9411c.png)

After:

![screenshot_2017-01-19-23-53-06](https://cloud.githubusercontent.com/assets/22588035/22120437/ac355d9a-dea5-11e6-89ae-6741cbf49002.png)

**Comment by heysadboy** [comment]
@the-dagger Review this issue please. I made a pull request also.

**Comment by the-dagger** [comment]
Hey @heysadboy, thanks for the issue.
But my suggestion is to send a PR for a UI enhancement/ Feature implementation only after there has been a discussion on that issue.

Regarding this issue, I don't think that the sessionDetail needs a UI refresh because that collapsingToolbar is a placeholder and any image provided by the speaker for the event will be placed there.
We can probably make enhancements similar to these to once the app's UI looks mature enough.

Cheers.

**Comment by heysadboy** [comment]
@the-dagger I understand. Should we delete this issue? Main motive was just due to wide toolbar, which is not an issue after all. I'll look for other non UI issues. Thanks for reviewing.
