### ISSUE TITLE
Header Image of navigation drawer sometimes not appearing.

### ISSUE THREAD

**Issue by harshitagupta30** [fossasia/open-event-android#1040]
**Actual Behaviour**

![screenshot from 2017-01-21 22 44 34](https://cloud.githubusercontent.com/assets/12701036/22176986/aa8a3604-e03b-11e6-962b-937018c17e00.png)

**Expected Behaviour**

![screenshot from 2017-01-22 00 09 09](https://cloud.githubusercontent.com/assets/12701036/22177004/d0f03988-e03b-11e6-9da3-5596a92f611e.png)

**Steps to reproduce it**
Instead of providing the image src in the XML file if we specify in MainActivity.java file, the issue will be resolved.

@the-dagger Can I send the PR for the same?

**Comment by the-dagger** [comment]
That is an expected behaviour.
The header that you see is fetched from [https://github.com/fossasia/open-event/blob/master/sample/FOSSASIA16/event#L12](https://github.com/fossasia/open-event/blob/master/sample/FOSSASIA16/event#L12).
If the image over there gives 404, then the fossasia logo is shown, else the logo pointed by this URL is show.
