### ISSUE TITLE
Delete files from apk branch if not required

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#1062]
The development branch holds a number of files. It is unclear if they are needed in this branch, that is basically just there to hold the auto generated apk files e.g. travis, gitignore, kubernetes deployment script.

![screenshot from 2017-01-27 11-25-59](https://cloud.githubusercontent.com/assets/1583873/22367778/9b2075a6-e483-11e6-91e3-28e345b42ec6.png)

**Comment by mananwason** [comment]
@mariobehling makes sense but all these files are needed. travis is needed to run the build, meta/deployment/deploy.sh is needed to be run to deploy the apk to the branch as well as for cloud.

We can remove the license at max and move everything else in a seperate folder.

**Comment by mananwason** [comment]
@mariobehling @niranjan94 What should be done here then?

**Comment by niranjan94** [comment]
> mariobehling makes sense but all these files are needed. travis is needed to run the build, meta/deployment/deploy.sh is needed to be run to deploy the apk to the branch as well as for cloud.

> We can remove the license at max and move everything else in a seperate folder.

@mananwason I agree with you. 

@mariobehling The reason we aren't able to have google cloud deployments in the master/development in the google cloud branch itself, is Travis does not support android and docker builds simultaneously. And we need docker for Google cloud deployment. So, what I did is, 

For every push to dev, an apk gets generated along with some meta files (branch, commit hash) and gets pushed to the apk branch. And this push will trigger the gcloud deployment using the apk branch's travis script. (here we can use docker since there is no other build involved here)
