### ISSUE TITLE
How is Butterknife working?

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1082]
Going according to the docs we first have to update the build.gradle main and app module files and then we can use @BindView in our code.
My question  is everywhere in the code samples ButterKnife.bind() is used by people in the onCreate() function but couldnt find in the Open Event app. How is it working over here?

**Comment by harshitagupta30** [comment]
Hi @arp95! In the Open Event app code, every activity instead of extending the default _Activity_ class, they are extending the _BaseActivity_ class which means whenever we are creating a new activity it'll be overriding the BaseActivity methods.
 
In _onCreate()_ of _BaseActivity_,  we have called ButterKnife().bind which means all the activities will have it automatically. We need not call it every time in each activity.  

I hope it clears your doubt! :)

**Comment by arp95** [comment]
@harshitagupta30 yeah missed that part.
Thanks !!
