### ISSUE TITLE
Reduce size of repository

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#1094]
The repository is currently over 200MB. How can we reduce the size?

**Comment by arp95** [comment]
@mariobehling 
1. we can remove the libraries which are not of utmost importance right now. Like ButterKnife etc.
2. we can remove duplicate items, unused imports, unused drawables in the project.

**Comment by free4murad** [comment]
@mariobehling 
1. We can reduce the size of screenshots in the `docs` folder. The images size is abnormally large (some are even 1.8MB large). We can look into that.

Can I PR for this.

**Comment by iamareebjamal** [comment]
The repo size is large due to binary files like images and apk. For these resources, git cannot diff and only store incremental changes. It has to the store whole file.

As each commit builds a new apk, the apk branch contributes most to the size of repo and  will continue to grow. There are options for contributors like : 
1. Fetch/Pull only required branch. For eg: Pull master only and then create local development branch and pull it from origin. This will only cost you ~35 MB for master and then development branch will be a few hundred KBs as it is ahead of master by a few commits.
2. Use git-filter branch or BFG to remove the stale apk files from apk branch. But this requires rewriting history. Meaning, all contributors have to first pull from upstream and then commit. But as far as I know, no one commits directly to apk branch, so it would be the most viable option to actually reduce the size of repo.

**Comment by free4murad** [comment]
@iamareebjamal 
i don't think apk branch is contributing significantly towards the total repo size. The total size of apk branch is not more than 8MB.  Also the old apks are deleted from the apk branch when new ones are pushed.

**Comment by iamareebjamal** [comment]
@free4murad git stores the deleted files too. That's the whole point of version control, in case you want to go back in history. The actual size of the folder at a state is just the size consumed by the files currently in the repo. The old ones exist as well. 
Here, I just pulled only **apk** branch to show its size. It's 172 MB, which is **97%** of the total repo size of **177 MB**

Screenshot attached
![kazam_screenshot_00015](https://cloud.githubusercontent.com/assets/3874064/22856148/cda9e266-f0b1-11e6-8970-569bc2639d44.png)

**Comment by free4murad** [comment]
@iamareebjamal 
thanks for sharing this.

**Comment by betterclever** [comment]
@mariobehling I can apply a similar workaround here like I did on susi-android which reduced repo size from 1GB ~ 20mb, should I proceed?

**Comment by the-dagger** [comment]
@betterclever Sounds like a plan! 👍

**Comment by mananwason** [comment]
@betterclever Please let us know the changes that you plan to make.

**Comment by betterclever** [comment]
@mananwason Since already latest apk is required for testing purposes, we need not maintain all previous APKs that were generated, so a orphan branch can be made with just one commit, that maintains latest APK and current branch can be overwritten by that. 

You may refer the implementation here :smile: 

https://github.com/fossasia/susi_android/blob/master/exec/apk-gen.sh
