### ISSUE TITLE
Wrong speaker details appearing in SessionDetailActivity

### ISSUE THREAD

**Issue by brainbreaker** [fossasia/open-event-android#1112]
Session Detail Activity retrieves wrong speaker names for 'Every' session. This is a high priority bug for an app focused on events. 

**Actual Behaviour**

Session 'Mobile Development for Students' is by @mananwason but when you open session details of 'Mobile Development for Students' the speaker comes out to be 'Ulrich Nobisrath'. 

I would go through the approach I took to solve this bug: 
Here is the snap of code where we're fetching the list of speakers by session name, which gets called in SessionDetailActivity.

<IMG src = "https://s19.postimg.org/5eyxycrer/15822361_1222527417824016_136371074_n.png">

Notice the log statements put by me, this is the output in logcat: 

<IMG src = "https://s19.postimg.org/xdt3p7t1f/15840974_1222527794490645_550866248_n.png">

As you can see, cursor dump shows id=82 and 99 with session name "Mobile Development for Students". 
Below is the snapshot of session JSON in assets, for id 82 and 89 whose titles are not 'Mobile development with Students'
<IMG src = "https://s19.postimg.org/moatj7rur/15857557_1222528304490594_1065944628_o.png">

<IMG src = "https://s19.postimg.org/wzrrpm8xv/15870836_1222528297823928_1108483189_n.png">

So there is definitely some problem with either fetching or creation of tables in the app.
Coming to the actual thing which I could trace, the problem is in the creation of tables in the application:

<IMG src= "https://s19.postimg.org/5vk5ksf5v/16176707_1237556216321136_1145495312_n.png">

In these INSERT queries 'id' values are 1 less than those found in JSON. I'm not sure from where these INSERT query logs are coming, probably from the library.

There is a method to handle JSON data in MainActivity but it is not being called even when downloading the JSON. That I know because I tried putting log statements in the method, tried debugging but nothing came out of them.

These tables are probably made by using OTTO library in the application. @the-dagger and @mananwason I need your help to solve this.

**Comment by the-dagger** [comment]
@mananwason  Could you help @brainbreaker with this issue?

**Comment by divs4debu** [comment]
The logs of sessions are generated in [org.fossasia.openevent.api.processor.SessionListResponseProcessor](https://github.com/fossasia/open-event-android/blob/development/android/app/src/main/java/org/fossasia/openevent/api/processor/SessionListResponseProcessor.java)

![Code](https://s1.postimg.org/5c52ye79r/Kazam_screenshot_00022.png)

The session id and stored id are mapped and stored in another table and then the session is assigned new id according to the iteration of the loop maybe for arranging in the order of retrieval from the network.

Maybe the error arises from displaying the object directly using the original ID. rather than the mapped one.

- One solution is to modify the query and use appropriate join
- Create a new attribute for the mapped field in session rather than using a new table and sort using new attribute and show using the original id. This requires a little bit of schema manipulation but is better and less error prone for future usage

**Comment by SparshBansal** [comment]
@the-dagger I think i can be helpful in solving this bug. Can I?

**Comment by the-dagger** [comment]
Sure, please coordinate together to find a solution. :+1:

**Comment by brainbreaker** [comment]
@divs4debu Thanks for your input. I have solved the bug and initiated a PR for the same. You are also welcome to review it. :) 

Now, we use only one field `id` in Session class and table which matches the incoming Session IDs in JSON. The unique constraint in maintained. I have removed the ServerSessionIDMapping class and table because it was making things a bit complex and redundant. 
@the-dagger @mananwason Please review.
