### ISSUE TITLE
Displaying invalid email incorrectly

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#1178]
**Describe the bug**
Displaying invalid email on entering a valid email address. 

<img src="https://user-images.githubusercontent.com/27783786/53296993-9590d180-383c-11e9-8ed5-828e9d40439b.png" height = "480" width="270"> 

**Would you like to work on the issue?**

- open for all

**Comment by angmas1** [comment]
Can I work on this?

**Comment by angmas1** [comment]
@liveHarshit this is happening when using https://api.eventyay.com/v1/ and not on https://open-event-api-dev.herokuapp.com/v1/ I believe 1st api isn't fully working. Correct me if I am wrong. Moreover, it's a server side bug because server must be returning HTTP 422

<blockquote><div><strong><a href="https://api.eventyay.com/v1/">404 Not Found</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://open-event-api-dev.herokuapp.com/v1/">404 Not Found</a></strong></div></blockquote>

**Comment by liveHarshit** [comment]
@iamareebjamal Is there any issue with the server?

**Comment by iamareebjamal** [comment]
@CosmicCoder96 Can you please check?
