### ISSUE TITLE
Add Option to download event information on mobile data

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-android#1227]
**Actual Behaviour**

Right now data can't be downloaded on mobile data

**Expected Behaviour**

Since almost everyone uses mobile data today, it is imperative to have the option to download data on mobile data

**Comment by arp95** [comment]
@mananwason can i work on this?

**Comment by mananwason** [comment]
@arp95 I'm fixing this.

**Comment by betterclever** [comment]
@mananwason I've fixed this bug, can I send a PR? I may send a sample APK for you to check first if you wish to.

**Comment by mananwason** [comment]
Please send a PR for this one please. Have been a bit busy so wasn't able to fix it. 

Let's leave the proxy scenario for now.

**Comment by betterclever** [comment]
@mananwason There is also a issue when a user is using VPN? Should I raise a issue for both proxy and VPN , since user maybe using VPN services on his phone (common among corporates)

**Comment by mananwason** [comment]
@betterclever But the internet should be accessible both in the case of proxy as well as VPN, what do you wanna check for?

**Comment by betterclever** [comment]
Sorry, I wrongly placed a question mark in above comment. Point being , it is not currently accessible. I have checked it issue being currently explicit checks are being used for mobile data and wifi and VPN doesn't show up as both. Proxy is not working because the NetworkUtils explicitly check internet connectivity by making a ping request to google which fails if device is working in a proxy based environment.

**Comment by betterclever** [comment]
@mananwason Data is able to be downloaded on mobile data in its **current state** by toggling the preference. My bad, I **did not** notice that. Is this issue meant to serve a different purpose since **data is getting downloaded on mobile data in current state of the app**.

Extremely sorry for not noticing it earlier.
