### ISSUE TITLE
Displaying cached images using Picasso

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1326]
**Actual Behaviour**

Earlier in my issue i used Picasso to display cached images in SponserFragment. Extending that to all the parts having images.

**Expected Behaviour**

Display cached images when offline.

**Would you like to work on the issue?**

yes.

**Comment by iamareebjamal** [comment]
I recommend using synchronous observable method from NetworkUtils so that UI doesn't block when checking for connection.

See [this](https://github.com/fossasia/open-event-android/blob/development/android/app/src/main/java/org/fossasia/openevent/adapters/SponsorsListAdapter.java#L95)

Also, cancel the Picasso operation by tag if loading asynchronously. If we use if-else approach then immediate caching can't be performed by picasso as it waits for the connection callback to happen

:+1:

**Comment by iamareebjamal** [comment]
@arp95 and @Shailesh351, I think one of you two could take up this issue. It is very critical for the application. A 10 MB disk cache should be sufficient for Picasso configuration, and try to make it injected globally, i.e., from Application class so that there is no need for any special class and static accessors

**Comment by Shailesh351** [comment]
@iamareebjamal  i would like to work on it.
[Milestone 5](https://github.com/fossasia/open-event-android/milestone/28)
