### ISSUE TITLE
No Internet Layout displayed on rotation even when data is present in EventsFragment on connection loss

### ISSUE THREAD

**Issue by addiegupta** [fossasia/open-event-android#1341]
**Describe the bug**

The No Connection available card is displayed in EventsFragment on rotation if connection is lost after loading events and rotation takes place.

**To Reproduce**

1. Go to EventsFragment and let events load
2. Switch off Internet connection
3. Rotate device
4. See error --> The No internet layout is displayed even when data was present

**Expected behavior**

2 implementations can be made out of which 1 will be chosen
1) Display the no internet layout along with the pre loaded data (I prefer this)
2) Display just the pre loaded data

If anyone has any suggestion on this please let me know!

**Screenshots**

![Issue 1341](https://user-images.githubusercontent.com/22665789/54553931-4e2fd800-49d9-11e9-84e4-dedee3873af7.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Nokia 6.1 Plus|
|Android Version|Pie 9.0   |

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by AnEnigmaticBug** [comment]
This issue is there because the `EventsFragment` is checking the internet connectivity in the `onCreateView` method.

After loading the data, when you rotate the phone, the `Fragment`'s view is recreated and `onCreateView` is called again. Because the check happens in `onCreateView`, it ignores whether the data has already been loaded or not and simply displays the "No Internet" layout.

I see two possible solutions to this problem:
1. Check whether `events.value` is non null and non empty. If it is, display the events. Otherwise check for the internet connectivity.
2. Move to logic for checking internet connection into the `EventsViewModel`.

Here's my take on the two solutions:
1. Solution1 will be the easier of two and will take minimal changes to fix the bug. But it doesn't improve the code.
2. Solution2 will take slightly more effort but will improve the code by moving logic from `EventsFragment` to `EventsViewModel`.

**Comment by liveHarshit** [comment]
IMO, using the view model is a better solution.
