### ISSUE TITLE
Feedback Section of the Entire Event

### ISSUE THREAD

**Issue by RamolaWeb** [fossasia/open-event-android#1377]
**Actual Behaviour**

Currently there is no such feature for the participant of the event to give feedback about the entire  event in the app. Thus participants cannot  give valuable feedback to the organizer of the event.  

**Expected Behaviour**

There must be a section regarding the Feedback where the organizer can raise some multiple choice question regarding the event and then each user can give the rating by selecting the options.

**Would you like to work on the issue?**
Yes I would like to work on the issue.

**Comment by iamareebjamal** [comment]
Until there is a feature like that on the server, we can't do much about it. Think of it this way:
- Who is authorised to post feedback (people with ticket? any authenticated user? what should be the mode of authentication?)
- Who is authorised to monitor the feedback?
- How are feedbacks sent to server (they can't until there's an API for it)

In short, there needs to be various steps between being able to implement this feature. Following being the most crucial :
- Authentication
- Server Support

**Comment by mariobehling** [comment]
Exactly, feedback will not go in as long as the server does not have it. Let's get the basic features of this app ready and follow up on other ideas when there is time.

**Comment by simarsingh24** [comment]
@iamareebjamal I think we should reopen this as per our discussion at #2293

**Comment by simarsingh24** [comment]
@iamareebjamal what I am proposing is a menu item "Submit Feedback" which would launch an activity related to feedbacks where the user (Logged in) can submit his/her feedback. how does this sound to you? and also since the feedbacks are somewhat like the review of the event so should other submitted feedbacks be shown to the user?
<img width="303" alt="screen shot 2018-02-14 at 2 07 45 pm" src="https://user-images.githubusercontent.com/16715499/36194637-8064baac-1190-11e8-8eb9-7d201989ee91.png">

**Comment by simarsingh24** [comment]
@iamareebjamal is this a good idea? please let me know so that i could proceed further with it

**Comment by iamareebjamal** [comment]
Yes, please go ahead and yes, show the feedbacks to the user
