### ISSUE TITLE
SearchView Widget Not Working

### ISSUE THREAD

**Issue by aggarwalpulkit596** [fossasia/open-event-android#1423]
**Describe the bug**
SearchView Widget in searchFragment is not working is always shows no result for any text searched
**To Reproduce**

|               | |
|---------------|-|
|Device         |Oneplus 3|
|Android Version| Oreo 8.0 |

**Would you like to work on the issue?**
- [x] Yes

**Comment by anhanh11001** [comment]
It's not always the case. Maybe if you try typing "Fossasia" in that along with "Singapore" in the location text, "Anytime" in the time text, it would return some results. The searchView along with the two edit text below together form the query, you should take a look at the API and. I think the main problem here is that the SearchFragment, in general, is not user-friendly so that's why some people don't understand how that work and cannot get any results

**Comment by aggarwalpulkit596** [comment]
@anhanh11001 it should work similar to implementation AFAIK Eventbrite
