### ISSUE TITLE
The app start screen shows "FOSSASIA" - it should show the basic event info and logo

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#1443]
The app start screen always shows a FOSSASIA logo. It should be showing the event logo and basic info. Please implement a start screen with the following info:

* logo of event
* Name of event
* tagline if any
* Date or dates
* location

Please ensure it looks "cool".

**Comment by harshitagupta30** [comment]
@mariobehling @the-dagger I've created a similar page screenshot of which is attached. Let me know if it looks good to you. Also due to some issue, it was merged and reverted later. I'll make sure before sending the PR that those issues are resolved. :+1: 
https://cloud.githubusercontent.com/assets/12701036/23942780/638dce60-0993-11e7-9ce9-c5a68f03e613.jpg

**Comment by harshitagupta30** [comment]
P.s. The details mentioned here will be event specific. I have take FOSSASIA just for the demo.

**Comment by betterclever** [comment]
@harshitagupta30 I guess issue is about start/splash screen and not About Page, although that addition can also be considered.

**Comment by harshitagupta30** [comment]
@betterclever Hi as mentioned in above comment we need to add logo of event, Name of event, tagline, 
Date or dates, location to the main screen which is already there in this screen and solves the purpose. We can modify it according to that if in case.
@mariobehling, In my opinion, we can create splash screen which will display the logo of the event like currently, we have FOSSASIA, for OSCAL we can put their logo. Also after the splash screen, we can have about screen because we can't add so many details to the splash screen. Since its purpose is to display something on the screen for the time the data is being loaded in the background instead of the blank screen.

**Comment by betterclever** [comment]
@harshitagupta30 the details required can be mentioned on the Splash Screen itself like Udacity Intersect App.

**Comment by harshitagupta30** [comment]
@betterclever I guess in Udacity Intersect App the splash screen is an image designed containing details not a screen with multiple textviews. In our case, since it's a generalise app not specified to a particular event we can't design an image for each event. We have to explicitly add details in form of textview which in my opinion, not a good idea.

**Comment by betterclever** [comment]
@harshitagupta30 I know that, but it can be done easily as well. While generating app, we can populate a  eventinfo.xml with event specific information in form of String Resources, the TextViews can utilize same resources so not much explicit addition is required as such.
In my opinion some Splash will be better if we provide required info. "About" screen is a nice addition too and I guess both can/should be adopted. 
@the-dagger Please clarify which approach shall we adopt?

**Comment by the-dagger** [comment]
@harshitagupta30 @betterclever 
I believe both splash screen and the about us page should be there.

We reverted the existing about us page because there were some issues with it (lacked auto refresh, toolbar auto hide, swipetorefresh)

If you want to implement it again, I'm more than happy to review it.

**Comment by harshitagupta30** [comment]
@the-dagger I've no issues in implementing it again but I'll do once I get free from my end semester exams. :) Also I and @betterclever I discussing whether to add details about the event in the splash screen or not. Please let us know.

**Comment by iamareebjamal** [comment]
I think only logo would suffice on Splash screen as on hot reloads, it only loads for fraction of a second. We will just need to configure the apk generator to also replace the splash logo drawable while generating the apk. I tried setting up the apk generator environment and succeeded, but I could not debug why the generator was failing in generation of app

**Comment by mananwason** [comment]
@harshitagupta30 Let's keep the logo only on the splash screen as @iamareebjamal said. @iamareebjamal What issues are you facing?

**Comment by iamareebjamal** [comment]
I start redis and celery with gunicorn as shown in the development docs and the generator app is loaded just fine, but neither can I see any log I write in the code, nor any exception that I throw, the app generation fails silently with the error message on the web app and no message on any of the console. 

I tried many command line arguments to gunicorn about log level, log file, enabled flask debug mode, tried both the logging module and print statement, but to no avail
