### ISSUE TITLE
Unscheduled Session show up at 0:00

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#1448]
Unscheduled sessions show up in the schedule at 0:00. Expected: Do not show unscheduled sessions at all. 

Ensure unscheduled sessions show up in the API accordingly and align with the event orga server. Do not just mark a session "unscheduled" if it starts at 0:00. It is possible that there are sessions at that time actually. Please take care to details in this issue.

**Comment by heysadboy** [comment]
@mariobehling Can I work on this?

**Comment by harshitagupta30** [comment]
@heysadboy go ahead :+1:

**Comment by heysadboy** [comment]
@mariobehling @harshitagupta30 Hey, events at 00:00 shows up like this 


![screenshot_2017-05-05-20-05-46](https://cloud.githubusercontent.com/assets/22588035/25750687/182700f8-31d0-11e7-98e3-fb47e6e6ff83.png)


I am not able to reproduce this bug. Am I missing something? Is this the expected behavior?

**Comment by mananwason** [comment]
@heysadboy This is because events at 12 PM are decoded as 12 AM and rendered at 00 times. Take a look at ISO conversions.

**Comment by heysadboy** [comment]
Okay, solving this here https://github.com/fossasia/open-event-android/pull/1538. Please see @mananwason .

**Comment by heysadboy** [comment]
Target Milestone to solve the issue

https://github.com/fossasia/open-event-android/milestone/24

I can't edit this issue so putting this here.
