### ISSUE TITLE
DayScheduleFragment leaked 109 KB

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1489]
**Actual Behaviour**

After using the app for a while i get a notification as seen below for the information leakage.

**Expected Behaviour**

Adding appropriate permissions in the manifest file to avoid that.

**Steps to reproduce it**

1. Use the app for several minutes.
2. While doing so go to different items like tracks, location, schedule etc.
3. You will get a notification of information leaked.

**LogCat for the issue**

-

**Screenshots of the issue**

![18361852_10211217388265000_881712396_o](https://cloud.githubusercontent.com/assets/8268392/25770726/02f4a420-325b-11e7-924a-398833941943.png)

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
@arp95 This is the message from LeakCanary. Once you click on the notification, it'll ask for the permission to access storage once and after that you can see the leaks in the app called `Leaks` on your device. This was working as expected on Nougat when I last tested. Is your app behaving differently than expected?

**Comment by arp95** [comment]
@iamareebjamal
actually i tried to open the app different times but after a while i get that leak notifcation.
In the Android Monitor it shows we have to add permission for writing external storage.

**Comment by iamareebjamal** [comment]
It is just a warning because the library manifest declares that permission and the app doesn't.

We should not add that permission in production code because leak canary won't be shipped in release builds and it will add an unnecessary permission to our app.

I recommend you to wait for another leak or make it happen temporarily and it will be shown just fine. If not, we can look into it

**Comment by Shailesh351** [comment]
I have also observed same notification and observed that the leak is
because of DayScheduleFragment instance

**Comment by iamareebjamal** [comment]
True. I removed the SwipeRefreshListener in `onDestroyView` but it is still leaking somewhere. Fixing that issue will non conventionally fix this issue as well @arp95

**Comment by arp95** [comment]
@iamareebjamal
are you facing this issue?

**Comment by Shailesh351** [comment]
Screen shot for the same : 
![leak](https://cloud.githubusercontent.com/assets/18264684/25772231/48d11054-3284-11e7-855e-8cba7af37c40.jpg)

**Comment by iamareebjamal** [comment]
The issue is not about the permission, but the memory being leaked which is being reported by leak canary 

Details can be seen when you open the notification
![device-2017-05-06-175139](https://cloud.githubusercontent.com/assets/3874064/25772250/b663f3ac-3284-11e7-8ef5-a49075647198.png)

Try to remain at schedule fragment for a period of time, it should show up

**Comment by arp95** [comment]
@iamareebjamal
yeah was getting this. although the solution might not be as you said will have to look up on the android monitor for further details

**Comment by iamareebjamal** [comment]
The solution to the leak or permission problem?

**Comment by arp95** [comment]
what i meant is you might be right permission might not be a solution for this.

**Comment by arp95** [comment]
resolved the issue. working fine on my device.
submitting the pr in a while.
Thanks for help @iamareebjamal !

**Comment by iamareebjamal** [comment]
Great!
