### ISSUE TITLE
Problem with loading colours.

### ISSUE THREAD

**Issue by m-murad** [fossasia/open-event-android#1524]
**Actual Behaviour**
Issue similar to #1452 can be observed in LocationFragment.

**Steps to reproduce it**
In LocationFragment click on any location and the behaviour can be observed.

**Would you like to work on the issue?**
@iamareebjamal You solved the last one. Please have a look into this aswell.

**Comment by iamareebjamal** [comment]
Sure.

It should be working fine, but I'll take a look

And if the Realm PR #1509 is approved, we won't need separate color loaders

**Comment by free4murad** [comment]
Actually, we are not using the `storeColor()` or `getColor()` method of the `TrackColors` in `LocationFragment.java`. So this behaviour is expected.

Also a lot of work in #1509. If you need some help with it please let me know. I can help you after 12th of this month.

**Comment by iamareebjamal** [comment]
That's when my exams will get started, so that will align perfectly. Dedicating whole day and night till that to make up for it :stuck_out_tongue_winking_eye: 

About this issue, I might have forgot to do that in LocationFragment, doing it now. Thanks for mentioning

**Comment by iamareebjamal** [comment]
Took a look at `LocationFragment`, actually there is no need to use cached colors there because location does not have its own color. It is handled by `SessionListAdapter` as each item in it will have a different track and thus different color, and we are using the cached colors there.

The reason there is a delay in loading the color is that the color for that track is not cached yet, and once it is loaded, it will be cached for upcoming tracks. This delay will be shown once for each track but is not apparent on TracksFragment as it takes time to load itself.

There are two solutions to this:
- Add color field in parsingExtra `Track` to save in db, so no lazy load is required
- Lazily load all track colors into cache at beginning of application

Both these solutions will be redundant once the Realm migration is complete. So I think it is better to wait.

Let's see what the mentors think.

@the-dagger @mananwason

**Comment by the-dagger** [comment]
@iamareebjamal since the realm migration is complete so I think that we should close this issue.
