### ISSUE TITLE
New Tracks Fragment UI proposal

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-android#1649]
I have made some mocks to discuss a new, and more material UI for tracks fragment. Let's discuss if they are better than the current one.

UI 1 : 
![device-2017-06-03-234144](https://cloud.githubusercontent.com/assets/3874064/26756098/e83f5908-48b8-11e7-9840-ebae33f32ee8.png)

UI 2 : 
![device-2017-06-03-234648](https://cloud.githubusercontent.com/assets/3874064/26756099/eec5f6f6-48b8-11e7-9fd4-af70ed033cec.png)
![device-2017-06-03-234903](https://cloud.githubusercontent.com/assets/3874064/26756100/f5282f50-48b8-11e7-8b69-fd88b84b0aa8.png)

UI 3 : 
![device-2017-06-03-235146](https://cloud.githubusercontent.com/assets/3874064/26756103/fe2f2338-48b8-11e7-8507-8170a836c64d.png)
![device-2017-06-03-235002](https://cloud.githubusercontent.com/assets/3874064/26756104/06010626-48b9-11e7-9109-9d0cd87b319f.png)

Personally, I like UI 3 the most. Please let me know what you guys think

**Comment by iamareebjamal** [comment]
@the-dagger @mananwason @mariobehling What is your take on this?

**Comment by shreyasnbhat** [comment]
@iamareebjamal Could you explain what is different between UI2 an UI3?

**Comment by arp95** [comment]
i would prefer ui3. looks good to me

**Comment by shreyasnbhat** [comment]
@iamareebjamal We could also add a small detail at the side indicating the number of sessions of each track on the track card.

**Comment by iamareebjamal** [comment]
@shreyasnbhat Yeah sure

And about the difference, the dark and light colors are inverted in both

**Comment by mahikaw** [comment]
UI-3 looks good I think.

**Comment by mahikaw** [comment]
@iamareebjamal I think there should be an option in the action bar to select a grid layout or list layout. Not everyone prefers to look at grids in my opinion.

**Comment by Shailesh351** [comment]
@mahikaw right. Just like Google drive app. UI should be flexible.

**Comment by mahikaw** [comment]
Also, @iamareebjamal since the tracks, alongwith their descriptions consist of primarily textual content, it will be better to continue with list layout. According to guidelines, grid layouts should be used when the content has distinguishing image icons with very little or no text.
The Google I/O 2017 app too consists of just a list layout for tracks.

**Comment by shreyasnbhat** [comment]
@iamareebjamal  We could have something like the google play store design where we have a track and under the title of the track we have a horizontal recycler view with cards of the sessions of each track.
And this could a vertical recycler view for all tracks

**Comment by iamareebjamal** [comment]
@mahikaw The problem is that the current UI looks very ancient. If you could propose a good list based design, it'd be great

@shreyasnbhat Wouldn't it be unmanageable for big events where lots of sessions are present in the track. I think it'll confuse the users and make track detail activity obsolete

**Comment by shreyasnbhat** [comment]
@iamareebjamal  We could have it similar to the Google PlayStore as I said. Just load the first 4-5 sessions within a track and then add a button like MORE above the track card so as to access the other sessions

**Comment by mahikaw** [comment]
@iamareebjamal The mock ups that you have created are good enough but I feel that the current UI looks good and is very similar to the latest Google I/O as well as WWDC event apps. The maximum we can do is change the font to jazz it up a bit.
There is a need to focus on more critical issues than changing UI. However, this is just my view. 
@mariobehling @mananwason @the-dagger @niranjan94 will surely be able to guide better. 
 I can work on making it look more similar to the I/O app if it is intended by the mentors. 😄

**Comment by shreyasnbhat** [comment]
@mahikaw I guess we can have a separate design which would be influenced by the I/O app and the WWDC app. :)

**Comment by iamareebjamal** [comment]
@Hariofspades Please recommend what would be the better approach

**Comment by Hariofspades** [comment]
Thanks for including me. Will study the app completely and will get back in
couple of days here.

**Comment by Hariofspades** [comment]
Based on all of your inputs in this thread, I have created a design with couple variations. For tracks, I took the following use cases.

- User should be able to browse and find the item
- They can also search.
- Returning user: who has already visited the track (should be able to find it easier)


So for a list display, including the choice of grid and list is a good option(somebody suggested here).
Here's the sample on the grid style.

## Grid design
![mobile - grid - 1](https://user-images.githubusercontent.com/12189957/27214983-e3fca534-528c-11e7-82bd-28bdeb29160b.png)

### Design specs 

- Attractive look with small icon images
- Can be dedicated colour for each(random is also okay)
- Sticky header (already present)
- **Grid, can showcase more items in a single viewport**
- If images is not given, a text item with 2 letters (breaking monotonous)
- Sessions (good to have)
- As sorting is by alphabetical order, keeping the intelligent scroller is a good option (returning user can easily find it, rather than searching and finding, Eg: if he wants to find an item which is at the last, he has to search or type. With this, it will be flexible) 

## List design - variation 1

![mobile - list - 1](https://user-images.githubusercontent.com/12189957/27215207-cf2a6032-528d-11e7-8246-f9594d210473.png)

## List design - variation 2


![mobile - list - 2](https://user-images.githubusercontent.com/12189957/27215290-2194b89a-528e-11e7-9555-c66c3e62b4fa.png)


### Design specs for List Design

- Attractive look with small icon images
- Can be dedicated colour for each(random is also okay)
- Sticky header (already present)
- **List, can showcase less items  with more detail in a single viewport**
- If images is not given, a text item with 2 letters (breaking monotonous)
- Sessions (good to have), added as **tags**
- As sorting is by alphabetical order, keeping the intelligent scroller is a good option (returning user can easily find it, rather than searching and finding, Eg: if he wants to find an item which is at the last, he has to search or type. With this, it will be flexible)
- For variation 1, its square and for variation 2 it's circle (we can choose anyone)

## General Notes
- I have made the toolbar white, giving more professional and clean UI. Red does not signify much of an event and pleasant colour for me (not sure, whether it is configurable when generating event apk) ; feel free to correct me.
- I have added the images because, having only text drawable will be very monotonous. Also, if you're using this [library](https://github.com/amulyakhare/TextDrawable) ; then there is a memory dump happening. Refer to this [issue](https://github.com/amulyakhare/TextDrawable/issues/37)

Let me know if you guys like this. If not can bring up something as well.

Thanks.

**Comment by Shailesh351** [comment]
@Hariofspades Nice mocks!! Go ahead

And for toolbar color we are going to add feature to customise app (primary color / secondary color etc) in future https://github.com/fossasia/open-event-android/issues/1552 Thanks

**Comment by iamareebjamal** [comment]
We cannot use icons as it is not supported by the API, that's why we use TextDrawables. Other than that. Nice mocks :+1:

**Comment by Shailesh351** [comment]
@iamareebjamal We can use track_image_url

**Comment by iamareebjamal** [comment]
That's a full bleed real life image, not an icon. Besides we do need to provide support for it. Please create a new issue for that. We miss that because most of the time it isn't present

**Comment by niranjan94** [comment]
@Shailesh351 where does this `track_image_url` come from ?

**Comment by arp95** [comment]
@niranjan94 tracks json file.

**Comment by niranjan94** [comment]
@arp95 I'm not sure when and how these things got into the samples in the first place. But, as of now, we do not have support for track images. 

Also, see https://github.com/fossasia/open-event/wiki/%5BNextgen%5D-Open-Event-Universal-Format-Specification for the updated Open Event Universal spec that will be used along with the new API.

**Comment by Shailesh351** [comment]
@niranjan94 In the response of server for tracks it as attribute `track-image-url`
https://eventyay.com/api/v1/events/6/tracks

**Comment by niranjan94** [comment]
@Shailesh351 it probably crept in during the very initial stages of the API a year back. But as of now, there is no plans of supporting it and it will not be available in the nextgen API.
