### ISSUE TITLE
Improving the UI of speakers fragment

### ISSUE THREAD

**Issue by heysadboy** [fossasia/open-event-android#1658]
**Actual Behaviour**

When we sort according to name, country or organisation we don't actually see that information. 

**Expected Behaviour**

I think we should also display that information. By putting that up in list view like in tracks, where we can see the country instead of alphabets when we sort on the basis of country, similarly for organisation.

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

Milestone 5

**Comment by iamareebjamal** [comment]
@heysadboy Milestone 4 expired yesterday

**Comment by heysadboy** [comment]
@iamareebjamal Sorry my bad, add it to milestone 5.

**Comment by mahikaw** [comment]
@heysadboy I am unable to understand what you're pointing at. Could you please be more specific.

**Comment by heysadboy** [comment]
@mahikaw My idea is to display information like country name -> all the speakers of that country and organisation -> speakers of that organisation, when we sort the list according to that. Currently the grid is sorted but we don't see this info. like country name etc. i.e., the parameter of sorting. I'll add screenshots once I progress to make it more clear.

**Comment by mahikaw** [comment]
So basically you are suggesting that we add an indication somewhere on the screen that tells the sorting criteria presently?

**Comment by heysadboy** [comment]
Not somewhere. Similar to tracks on the places of alphabets.

**Comment by shreyasnbhat** [comment]
@heysadboy You are saying that we must add a sticky headers to the list right?

**Comment by heysadboy** [comment]
Sure @shreyasnbhat . Also get opinions if we could improve this in any other way.

**Comment by shreyasnbhat** [comment]
@iamareebjamal @arp95 @mahikaw @heysadboy We could remove the `FrameLayout` we are using on top of the speaker as it covers most of the speakers face. We could move it into a separate `TextView` below.And stickyListHeaders could be added here too. And we could also make the images circular as we have done this in `SessionDetailActivity`

**Comment by iamareebjamal** [comment]
@shreyasnbhat Or we could just reuse the layout and adapter made for SessionDetailActivity

**Comment by shreyasnbhat** [comment]
Yeah I guess that would be better.

**Comment by shreyasnbhat** [comment]
@iamareebjamal I'll start working on this now. If all these changes are acceptable.

**Comment by iamareebjamal** [comment]
Let's wait for the mentors to confirm

**Comment by the-dagger** [comment]
@shreyasnbhat Could you add a mock on what you are proposing?
This can be a rough sketch as well.

**Comment by shreyasnbhat** [comment]
![image](https://user-images.githubusercontent.com/19890557/26864715-2f5596ca-4b77-11e7-98c7-22cb975e33f7.png)

Ignore the toolbar. It wouldn't look like that.
@the-dagger I was thinking on these lines. We just need to add minor tweaks to make the image round instead of square. And also the text on top of the image hides most of the image. I feel that this would look better.
@iamareebjamal @arp95 @mahikaw @heysadboy Opinions?

**Comment by the-dagger** [comment]
@shreyasnbhat
I think that's fine.
Once you open the detail activity for speaker, their complete pic is displayed anyways.
So makes no sense to go ahead and redesign it.

**Comment by shreyasnbhat** [comment]
@the-dagger I'm not saying if it is fine or not. I am saying that the same thing can be done better. 
We want the user to see stuff what us being shown to them. Maximum of the images have text covering the entire image. So either we can remove the image from the SpeakerFragment as we can see the image anyways in the detail activity or we could do this.  Now its your call.

**Comment by the-dagger** [comment]
@shreyasnbhat The whole idea is to show more info in less space.
If we go what you propose, it'll take more space since the text will take some extra space to be dispkayed. 
Also we definitely need to display the speker's image and name on the fragment as well, so I feel that the current implement is good enough.

**Comment by shreyasnbhat** [comment]
@the-dagger As the image doesn't need to be as big as the current one. We could use the viewholder I made while doing global search.

![image](https://user-images.githubusercontent.com/19890557/26865596-0d2b0496-4b7b-11e7-8537-a42467e05cf3.png)
Something like this with a white background and a round image instead of a square. This would definitely take up lesser space.

**Comment by the-dagger** [comment]
So that means a single image per row, not that good as compared to the current implementatiion.
Not sure what's the issue here.
Even Google I/O 2015 used a similar speakers UI so I think it's good.

I'll recommend using the current viewHolder for the global search instead.

However regarding circular images instead of square ones, that is something you can do, but I'm sure that we tried it earlier and it didn't look that good with the current UI.

**Comment by shreyasnbhat** [comment]
@the-dagger Alright.
But for the global search it wouldn't look good if we use this ViewHolder and I have discussed about this in detail already. Basically I am using a LinearLayoutManager and this layout works better with a GridLayoutManager. I have tried using this layout but it didn't look good.

**Comment by the-dagger** [comment]
Ok then.
If it has already been discussed, it's good to go ahead with the outcome agreed upon .
