### ISSUE TITLE
Alert dialog buttons are functioning reverse in attendee fragment

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#1882]
Currently - 
Are you sure to want to cancel the order?
click continue -> dialog dismiss
click cancel -> Order cancel

It should in reverse. 

**Would you like to work on the issue?**

- [x] Yes

**Comment by ShridharGoel** [comment]
I would have recommended to use `Yes` or `No` here since upon seeing "Are you sure to want to cancel the order?" some users might click on `Cancel` to proceed for cancellation. Maybe this is the reason that earlier it was in reverse order, `Continue` meant to continue with the order and `Cancel` was meant for cancellation of the order.

**Comment by liveHarshit** [comment]
@ShridharGoel Agree with it.
