### ISSUE TITLE
Create a simple Android App Generator page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#371]
The current way of building an app works for event organizers that have a developer at hand. However it does not work for event organizers who want a standard app that they can download.

Please explore and suggest a way how the app can be generated on a server through a simple web page, where an organizer can choose to upload a JSON file and generate the app that can be downloaded as an apk file or alternatively use the REST API of the orga server.

We need this:
* Give me a UI/User flow ASAP
* Construct with a UI
* Read a JSON and display the data
* Allow me to download the entire Android app as an apk
* Call from a REST API URL later for hosted mode

**Comment by the-dagger** [comment]
Sure @mariobehling, will get back to you with a User flow by tonight.

**Comment by mananwason** [comment]
@mariobehling @the-dagger first we need to change the way the app works. To generate a personalised apk, we need to make styles for each component of the app so that we can write a script that changes the theme and color of the app according to the organiser's preference. I'll create an issue for abstracting these styles meanwhile you can work on this issue and try to generate a sample apk from the source of the current master.

**Comment by mariobehling** [comment]
@mananwason Before we proceed implementing new features, we should actually implement this feature. The fact is, that most event organizers are not technical and do not have developers. So, creating a personal apk is a basic feature, that we need before any other features.

**Comment by mananwason** [comment]
Sure @mariobehling. I understand. @the-dagger will start working on this till then I'll create a customisable style. If the style is not customisable, the organiser won't use the app because they'll have the same theme and appearance as the sample app and they would have to ask a developer to change the appearance of the app which defeats the purpose

**Comment by mariobehling** [comment]
@mananwason Yes, it is correct, we need the style to be configurable, but the first basic version does not need to have this feature. Building the same app with the same style for different events would make a good first app. Hope we can have such a first version quickly.

**Comment by mananwason** [comment]
Sure @mariobehling I'll work on it and deliver it asap

**Comment by the-dagger** [comment]
@mariobehling Here is a proposed user flow, can you have a look at it and let me know if anything is to be changed.
[https://docs.google.com/document/d/1mCND9tIQNAZzXczmdoSzzJY4ErT0YvMUfDd-D-GdNEg/edit?usp=sharing](url)

**Comment by championswimmer** [comment]
Since Harshit asked my views on this  - 

@the-dagger @mananwason 

Some inputs from my side : 
 - Create a config.json in assets folder
 - In your java code, load config.json in Application#onCreate() 
 - Save the configs statically (or in shared prefs)
 - The configs can be stuff like 
   - URL of api endpoint
   - color of titlebar
   - layout of session (card vs list); if you have such a modifiable UI in future
   - you get the idea right ? 
 - Now in runtime use these static/pref values to 'inflate' everything. Use the color from the config.json in setTitleBarColor(), use the API endpoint in config.json with Retrofit/Volley. 

Now make a simple website with a form in which users can write their api endpoint, event id, event color, package name etc. 
Keeping all files exactly same, just regenerate config.json and AndroidManifest.xml (for the package name), then package into apk and distribute.

**Comment by the-dagger** [comment]
Cool, that makes sense @championswimmer .
Also please have a look at the user flow linked above
above. 
I have tried to make it in a step by step manner as you said earlier.
Cheers.

**Comment by mananwason** [comment]
@championswimmer good idea. I was also thinking of the same but for colors and theming I was thinking of making styles for each and every component and then modify the theme and color scheme of the app by generating a new styles.xml. This would make it even more customisable.

**Comment by the-dagger** [comment]
@mariobehling I was wondering whether the web page used for generating a custom .apk should be a part of the main FOSSAasia website or will it be a standalone website?

**Comment by mananwason** [comment]
@the-dagger doesn't really matter but let's keep it as a separate repo for now. I'll make a new repo for this.

**Comment by the-dagger** [comment]
Cool go ahead. 👍👍

**Comment by the-dagger** [comment]
@mariobehling Please have a look here [http://fossasia.github.io/open-event-android/](http://fossasia.github.io/open-event-android/)
Cheers.

**Comment by mariobehling** [comment]
Thanks for defining the specifics and requirements. Closing it. The details for building this are collected in this parent issue now: https://github.com/fossasia/open-event-android/issues/384
