### ISSUE TITLE
Update apk script

### ISSUE THREAD

**Issue by simarsingh24** [fossasia/open-event-android#378]
- [ ] When PRs are merged in the dev branch, add apks to the apk branch. Include “dev” in the name

 - [ ] When PRs are merged in the master branch, add apks using the master branch to the apk branch

 - [ ] Dev apks should only be updated when PRs are merged to dev. Master apks should only be updated when PRs are merged to Master.

**Comment by mariobehling** [comment]
Dev apks should only be updated when PRs are merged to dev. Master apks should only be updated when PRs are merged to Master. Please check with PSLab Android e.g. https://github.com/fossasia/pslab-android/tree/apk

**Comment by iamareebjamal** [comment]
@mariobehling This will render the orphan branch method useless and bloat the repo size to hundreds to megabytes in just 3-4 days and the repo size will only increase. Driving a lot of contributors away. Why don't we use Github's release mechanism rather than branch updation?

Selective committing will only increase the repo size and contribute to nothing else

**Comment by iamareebjamal** [comment]
`pslab-android` is now **450 MB** in size, whereas the development branch is only 11 MB. Just because they haven't set up the apk branch using orphan method
