### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#395]
Which other tests can we do with the code? 

Please add codeclimate and codecov. We are already using them on the orga-server.

**Comment by the-dagger** [comment]
On it @mariobehling :+1:

**Comment by mananwason** [comment]
@mariobehling We already have codecov. Codeclimate doesn't support android. We need to write more manual tests that can be run in travis builds but right now I don't think we should add more tests since I the priority should be to complete the app and all the features we have to add. We can start writing tests for these after the midterm evaluation.

**Comment by mananwason** [comment]
Already open in #171, so closing this
