### ISSUE TITLE
Implement more useful map page, e.g. currently map does not show address of event location

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#564]
* [x] As a first step add location info on map
* [x] Show a screenshot here what you plan to implement before making a PR

**Comment by mariobehling** [comment]
This issue is not entirely solved until we have the location address info in the app as well. If this is not provided by the API or sample file, please open an issue in the relevant component and help to fix this.

**Comment by mananwason** [comment]
Sure @mariobehling. Will do 👍

**Comment by the-dagger** [comment]
@mananwason I have modified `location_name` to correct address in the event json now.
[https://github.com/fossasia/open-event/commit/80e7a7920229df0e3cbb40bc9b46eab5291c3d7b#diff-9a23aeb01d885bc227132e2d2bde16e9R27](https://github.com/fossasia/open-event/commit/80e7a7920229df0e3cbb40bc9b46eab5291c3d7b#diff-9a23aeb01d885bc227132e2d2bde16e9R27)
Hope that helps.
Cheers.

**Comment by mananwason** [comment]
Sure @the-dagger I am working on changing the map UI but it may take 1-2 more day, so moving to next milestone

**Comment by mananwason** [comment]
@mariobehling This is fixed by changing the location name in the sample here https://github.com/fossasia/open-event/pull/69. 

This is the screenshot. So closing this issue now
![screenshot 22-aug-2016 10_52_27 pm](https://cloud.githubusercontent.com/assets/10570249/17864391/847b261e-68bb-11e6-8322-165259401957.png)
