### ISSUE TITLE
No error shown on entering wrong email

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-android#612]
@the-dagger Even if I add a random word, it doesn't show any error. It should check for a valid email and then proceed further

**Comment by the-dagger** [comment]
![screenshot_20160819_195751](https://cloud.githubusercontent.com/assets/6565270/17813037/47788a52-6647-11e6-9009-d8c27e3bec4d.png)
@mananwason Works for me.
Which browser are you using?
I tried with Firefox and Chrome

**Comment by mananwason** [comment]
@the-dagger Safari :/

**Comment by mananwason** [comment]
<img width="1437" alt="screen shot 2016-08-19 at 10 03 01 pm" src="https://cloud.githubusercontent.com/assets/10570249/17816810/bded3b0e-6658-11e6-8946-27ed4e04e82e.png">
Here is the screenshot

**Comment by Abhi2424shek** [comment]
Should I work on it,
I could provide javascript validation soon after you click the generate app. Searching for @ and . throughout the field and displaying an alert if nothing is there. Since it is javascript it should work for all browsers ranging from old ones. And since the code is small there should not be much of a delay too.

**Comment by the-dagger** [comment]
@Abhi2424shek Yep that's what I planned to do.
You can go ahead and work on this issue if you want :)

**Comment by Abhi2424shek** [comment]
sure @the-dagger

**Comment by Abhi2424shek** [comment]
Fixed it @the-dagger see the PR

**Comment by Abhi2424shek** [comment]
Please close this issue, it is solved and the PR is merged @mananwason @the-dagger . Happy coding :)
