### ISSUE TITLE
Implement local caching of events in room

### ISSUE THREAD

**Issue by simarsingh24** [fossasia/open-event-android#62]
working on it 👍

**Comment by simarsingh24** [comment]
to be done after #59

**Comment by nikit19** [comment]
I would like to help. Can I work on caching events?

**Comment by simarsingh24** [comment]
yes, please go ahead, I will work on user caching

**Comment by nikit19** [comment]
@iamareebjamal I am facing multiple issues in order to solve this.
I think I am having trouble understanding how koin works.
What I am trying to do is inject OpenEventDatabase in the EventsViewModel by passing it in the constructor
`class EventsViewModel(private val eventService: EventService,private val openEventDatabase: OpenEventDatabase) : ViewModel() {`
 but as soon as I do it I get an error in Modules.kt `No value passed for parameter 'openEventDatabase'`


After that I was thinking of using this instance to store the events in the db instead of MutableLiveData and then give this value to the user.
Could you also please explain the correct approach to this problem.
Thank you

**Comment by iamareebjamal** [comment]
First of all, you should inject it in EventService and not ViewModel

I'm looking into it
