### ISSUE TITLE
Please ensure all image formats and names work in zip and API

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#668]
There are cases where images might have international characters, spaces and formats. Please ensure that the app generator and API calls of the app are able to process these images.

This was discussed in project chats and issues before:
> The Android app only accepts images that have their name in lowercase and without any spaces.
This is not the case with images right now, so they are not getting displayed when the app is generated from the generator using sample zip file. https://github.com/fossasia/open-event/issues/100

**Comment by mariobehling** [comment]
To add some more background:

The goal is that lots of different projects to support our format. We hope to see wordpress plugins, drupal modules, ... everyone should use the format. If we restrict the formats all these projects in future will have to rename their files and implement our image restrictions. It is unlikely that e.g. the Drupal image module will implement our limits. And if a developer has to write another image plugin just to follow our limits it would reduce the probability that it will actually get done and our format get adopted.

Therefore it does not make sense to require these restrictions. As these restrictions are only relevant for the Android project they should be implemented in the Android project accordingly.

Are these restrictions only there when we use the app generator? What if we download the updates on the first run of the app? Can it read all files?

**Comment by the-dagger** [comment]
Yes it can read them during download
On downloading the images on first run, the format won't matter
It matters only during packaging images inside the generator.
We can do one this for this, in the speakers and sponsors json, we can have an additional field for the logo names `logo_url` that points to a URL containing the logo so that it can be fetched at run-time instead of packaging it with the app.

**Comment by mananwason** [comment]
@mariobehling We can parse any type of url i.e with spaces, special characters etc. in the app but while packaging images in the app we need to make sure that these images are png's and don't have any spaces or special characters for a successful build of the apk. 

We have fixed this to package the logo in the app but since for now we are not packaging any speaker images in the app, everything is working perfectly even with any kind of spaces or special_character i.e. if the URL is valid.
