### ISSUE TITLE
feat : show event location on maps in event details section as in event brite app

### ISSUE THREAD

**Issue by simarsingh24** [fossasia/open-event-android#83]
working on it 👍

**Comment by simarsingh24** [comment]
should i create google maps api key using my google account?

**Comment by iamareebjamal** [comment]
Yes, but it will not be committed to the repo. The changes should be made n such a manner that if there is no API key, app does not crash

**Comment by dreadpool2** [comment]
@simarsingh24 Can I work on this ?

**Comment by simarsingh24** [comment]
go ahead 👍

**Comment by dreadpool2** [comment]
@iamareebjamal Should I use the static maps API which provides us with an image with the marker on the place, just like this 
![staticmap](https://user-images.githubusercontent.com/28607714/41191546-f6610796-6c0e-11e8-943e-1aee7966abf9.png)

Because in the EventBrite app to this happens. When the map is clicked google maps opens with the required location

**Comment by iamareebjamal** [comment]
Yes

**Comment by dreadpool2** [comment]
Great!

**Comment by dreadpool2** [comment]
@simarsingh24 You can close this :+1:
