### ISSUE TITLE
Logical Error in number of Tickets shown when placing order.

### ISSUE THREAD

**Issue by kshitijsuri90** [fossasia/open-event-android#994]
**Describe the bug**

If 1 ticket is selected no box is shown for details as it is assumed that user is the customer but when 2 tickets selected 2 ticket boxes are shown for the input so the logic of user as the customer is not followed there.

**To Reproduce**

Buy 1 ticket first and then try again for two tickets

**Expected behavior**

Same logic pattern needs to be followed

**Logs**

**Screenshots**

![logic_ticket](https://user-images.githubusercontent.com/34534870/52084457-2969d780-25c8-11e9-99ac-8fecce3a9feb.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |One Plus 5|
|Android Version| Pie 9.0.3   |

**Additional context**

@liveHarshit @nikit19 @iamareebjamal Your views?

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by KVGarg** [comment]
I don't it is an issue because there may be situation where a user wants to book tickets for other people. 
Say, user A wants to book tickets 2 or more tickets excluding him. In that case, the 2 or more tickets will be filled with other user details and the information that is asked in beginning above the tickets, is the information about the user who has booked the tickets. 
And, I think there should be a ticket display for one user also, if going with above example.

**Comment by iamareebjamal** [comment]
Invalid issue unless an event is so awesome that you'd buy 3 tickets for yourself and your 2 clones
